[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
async-trait = "0.1.82"
clap = "4.5.20"
itertools = "0.13.0"

chrono = "0.4.38"
miette = "7.2.0"
reqwest = "0.12.5"
reqwest-middleware = "0.4.0"
tokio = "1.37.0"
tempfile = "3.10.1"
clap-verbosity-flag = "2.2.1"
tracing-subscriber = "0.3.18"
serde_yaml = "0.9.33"
serde = "1.0"
indexmap = "2.6.0"
minijinja = "2.3.0"

parking_lot = "0.12.3"

jsonrpc-stdio-server = "18.0.0"
jsonrpc-http-server = "18.0.0"
jsonrpc-core = "18.0.0"

url = "2.5.3"

rattler-build = { git = "https://github.com/tdejager/rattler-build", branch = "feat/upgrade-middleware", default-features = false }

rattler_conda_types = { version = "0.29.1", default-features = false }
rattler_package_streaming = { version = "0.22.14", default-features = false }
rattler_virtual_packages = { version = "1.1.10", default-features = false }
rattler_lock = { version = "0.22.31", default-features = false }



pixi_build_types = { git = "https://github.com/prefix-dev/pixi", branch = "feature/pixi-build" }
pixi_consts = { git = "https://github.com/prefix-dev/pixi", branch = "feature/pixi-build" }
pixi_manifest = { git = "https://github.com/prefix-dev/pixi", branch = "feature/pixi-build" }
pixi_spec = { git = "https://github.com/prefix-dev/pixi", branch = "feature/pixi-build" }


[patch.crates-io]
rattler = { git = "https://github.com/conda/rattler", branch = "main"}
rattler_conda_types = { git = "https://github.com/conda/rattler", branch = "main"}
rattler_package_streaming = { git = "https://github.com/conda/rattler", branch = "main"}
rattler_virtual_packages = { git = "https://github.com/conda/rattler", branch = "main"}
rattler_lock = { git = "https://github.com/conda/rattler", branch = "main"}
rattler_cache = { git = "https://github.com/conda/rattler", branch = "main"}
rattler_solve = { git = "https://github.com/conda/rattler", branch = "main"}
rattler_repodata_gateway = { git = "https://github.com/conda/rattler", branch = "main"}
rattler_redaction = { git = "https://github.com/conda/rattler", branch = "main"}
rattler_networking = { git = "https://github.com/conda/rattler", branch = "main"}
