[project]
name = "pixi-build"
version = "0.1.0"
description = "Binary for building pixi projects into packages"
authors = ["Tim de Jager <tim@prefix.dev>"]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "win-64", "linux-64", "osx-64"]

[tasks]
run-release = { cmd = "cargo run --release" }

build = { cmd = "cargo build" }
build-release = { cmd = "cargo build --release" }
run = { cmd = "cargo run" }


install-pixi-build-python = { cmd = "cargo install --path crates/pixi-build-python --locked --force" }
install-pixi-build-cmake = { cmd = "cargo install --path crates/pixi-build-cmake  --locked --force" }
install-pixi-build-rattler-build = { cmd = "cargo install --path crates/pixi-build-rattler-build --locked --force" }
install-pixi-build-rust = { cmd = "cargo install --path crates/pixi-build-rust --locked --force" }
install-pixi-backends = { depends-on = [
  "install-pixi-build-python",
  "install-pixi-build-cmake",
  "install-pixi-build-rattler-build",
  "install-pixi-build-rust",
] }

[dependencies]
rust = ">=1.86.0,<1.87"
python = ">=3.12.4,<4"
openssl = "3.*"
compilers = "1.6.0.*"
pkg-config = "0.29.2.*"
libzlib = ">=1.3.1,<2"
liblzma = ">=5.8.1,<6"

[target.linux-64.dependencies]
clang = ">=18.1.8,<19.0"
mold = ">=2.33.0,<3.0"
patchelf = ">=0.17.2,<0.18"

[target.linux-64.activation]
scripts = ["scripts/activate.sh"]

[feature.test.dependencies]
pytest = ">=8.3.2,<9"

[feature.test.tasks]
integration-test = { cmd = "pytest tests", depends-on = "build" }

[feature.release.dependencies]
python = ">=3.12.4,<4"

[feature.schema.dependencies]
pydantic = ">=2.8.2,<3"
ruff = ">=0.5.7,<0.6"

[feature.build.dependencies]
rattler-build = ">=0.30.0,<1"

[feature.build.tasks.build-recipe-ci]
cmd = "rattler-build build --test native --output-dir={{ output_dir }} --recipe {{ recipe }} --target-platform {{ target_platform }}"
args = ["output_dir", "recipe", "target_platform"]

[feature.build.tasks.build-recipe]
depends-on = [
  { task = "build-recipe-ci", args = [
    "./output",
    "{{ recipe }}",
    "{{ target_platform }}",
  ] },
]
args = ["recipe", "target_platform"]

[feature.schema.tasks]
generate-schema = "python schema/model.py > schema/schema.json"
fmt-schema = "ruff format schema"
lint-schema = "ruff check schema --fix"

[feature.lint.dependencies]
actionlint = ">=1.7.4,<2"
pre-commit = ">=3.7.1,<4"
pre-commit-hooks = ">=4.6.0,<5"
shellcheck = ">=0.10.0,<0.11"
taplo = ">=0.9.1,<0.10"
typos = ">=1.23.1,<2"

[feature.lint.tasks]
actionlint = { cmd = "actionlint", env = { SHELLCHECK_OPTS = "-e SC2086" } }
lint = "pre-commit run --all-files --hook-stage=manual"
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run --all-files"
toml-format = { cmd = "taplo fmt", env = { RUST_LOG = "warn" } }
toml-lint = "taplo lint --verbose **/pixi.toml"


[environments]
test = ["test"]
schema = { features = ["schema"], no-default-feature = true }
lint = { features = ["lint"], no-default-feature = true }
build = { features = ["build"], no-default-feature = true }
release = { features = ["release"], no-default-feature = false }
