name: Python bindings CI

on:
  push:
    branches: [main]
  pull_request:
    paths:
      # When we change code that bindings depend on, we want to ensure that the maturin builds still work
      - crates/pixi-build-backend/**
      - Cargo.*

      # When something in the bindings themselves changes
      - py-pixi-build-backend/**

      # Or when this workflow changes
      - .github/workflows/python-bindings.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  format_lint_test:
    name: Format, Lint and Test the Python bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: recursive
      - uses: prefix-dev/setup-pixi@fef5c9568ca6c4ff7707bf840ab0692ba3f08293 # v0.9.0
        with:
          manifest-path: py-pixi-build-backend/pixi.toml
          environments: ci
      - name: Format and Lint
        run: |
          cd py-pixi-build-backend
          pixi run -e ci fmt
          pixi run -e ci lint
      - name: Run tests
        run: |
          cd py-pixi-build-backend
          pixi run -e ci test --color=yes
